// togel class active
const navbarNav = document.querySelector(".navbar-nav");
document.querySelector("#hamburger-menu").onclick = () => {
  navbarNav.classList.toggle("active");
};

const hamburger = document.querySelector("#hamburger-menu");
document.addEventListener("click", function (e) {
  if (!hamburger.contains(e.target) && !navbarNav.contains(e.target))
    navbarNav.classList.remove("active");
});

// data
const biodata = {
  1997: [
    {
      foto: "ABDUL KARIM",
      nama: "Abdul Karim",
      no: null,
      tempat_tanggal_lahir: null,
      domisili: null,
      hp: null,
      pengesahan: "1987",
    },
    {
      foto: "MUHAMAD KARYA",
      nama: "Muhamad Karya",
      no: "041500023",
      tempat_tanggal_lahir: "Serdang Menang, 03 Maret 1983",
      domisili: "Serdang Menang",
      hp: "082372176010",
      pengesahan: "2004",
    },
    {
      foto: "DERY AWALAMUDDIN",
      nama: "Dery Awalamuddin",
      no: null,
      tempat_tanggal_lahir: ",12 Desember 1987",
      domisili: "Palembang",
      hp: null,
      pengesahan: "2003",
    },
    {
      foto: "YUDI UTAMA",
      nama: "YUDI UTAMA",
      no: null,
      tempat_tanggal_lahir: null,
      domisili: null,
      hp: "081958161371",
      pengesahan: "2003",
    },
    {
      foto: "RIZALUDIN",
      nama: "RIZALUDIN",
      no: "072300192",
      no: "072300192",
      tempat_tanggal_lahir: "Belanti, 07 September 1976",
      domisili: "Terate",
      hp: "0895622350952",
      pengesahan: "2007",
    },
  ],

  // Tambahan Batch 2 - Pengesahan 2009
  2009: [
    {
      foto: "SEPTA WINARTO",
      nama: "Septa Winarto",
      nomor: "091880037",
      tempat_tanggal_lahir: "Belanti, 15 September 1992",
      domisili: "Belanti",
      kontak: "085352514480",
      pengesahan: 2009,
    },
    {
      foto: "RINO INPER",
      nama: "Rino Inper",
      nama: "Rino Inper",
      nomor: "091880040",
      tempat_tanggal_lahir: "Terate, 14 Januari 1992",
      domisili: "Terate",
      kontak: null,
      pengesahan: 2009,
    },
    {
      foto: "LIBRA",
      nama: "Libra",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: "Terate",
      kontak: null,
      pengesahan: 2009,
    },
    {
      foto: "VETTY DWI VERA",
      nama: "Vetty Dwi Vera",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: "Terate",
      kontak: null,
      pengesahan: 2009,
    },
    {
      foto: "RANTI N",
      nama: "Ranti N",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: "Terate",
      kontak: null,
      pengesahan: 2009,
    },
    {
      foto: "ASRI HAIRIANDY",
      nama: "Asri Hairiandy",
      nomor: "091880091",
      tempat_tanggal_lahir: "Terate, 21 Oktober 1993",
      domisili: "Terate",
      kontak: null,
      pengesahan: 2009,
    },
    {
      foto: "HASAN BERIANDI",
      nama: "Hasan Beriandi",
      nomor: "091880093",
      tempat_tanggal_lahir: "Sp. Padang, 28 November 1994",
      domisili: "Rengas Pitu",
      kontak: "081366303014",
      pengesahan: 2009,
    },
    {
      foto: "ALIYA",
      nama: "Aliya",
      nomor: "091880092",
      tempat_tanggal_lahir: "Terate, 16 Desember 1995",
      domisili: "Bubusan",
      kontak: "088272088616",
      pengesahan: 2009,
    },
  ],

  // Tambahan Batch 3 - Pengesahan 2010
  2010: [
    {
      foto: "MUHAMMAD TESA",
      nama: "Muhammad Tesa",
      nomor: "101880130",
      tempat_tanggal_lahir: "Ulak Jermun, 09 Juni 1995",
      domisili: "Terate",
      kontak: null,
      pengesahan: 2010,
    },
    {
      foto: "VINA MEIWANDA",
      nama: "Vina Meiwanda",
      nomor: "101880132",
      tempat_tanggal_lahir: "Serdang Menang, 07 Mei 1992",
      domisili: "Serdang Menang",
      kontak: null,
      pengesahan: 2010,
    },
    {
      foto: "VITA APRIH",
      nama: "Vita Aprih",
      nomor: "101880131",
      tempat_tanggal_lahir: "Serdang Menang, 28 April 1993",
      domisili: "Serdang Menang",
      kontak: null,
      pengesahan: 2010,
    },
  ],

  // Tambahan Batch 4 - Pengesahan 2011
  2011: [
    {
      foto: "MIKI HARIAN",
      nama: "Miki Harian",
      nomor: "20101321758",
      tempat_tanggal_lahir: "Berkat, 15 Desember 1994",
      domisili: "Berkat",
      kontak: "082282500867",
      pengesahan: 2011,
    },
    {
      foto: "DIKA SAPUTRA",
      nama: "Dika Saputra",
      nomor: "20101321755",
      tempat_tanggal_lahir: "Serdang Menang, 06 Oktober 1994",
      domisili: "Serdang Menang",
      kontak: "+60182779465",
      pengesahan: 2011,
    },
    {
      foto: "RINI OKTAVIA",
      nama: "Rini Oktavia",
      nomor: "20101321748",
      tempat_tanggal_lahir: "Merah Mata, 25 Oktober 1994",
      domisili: "Serdang Menang",
      kontak: "081368257446",
      pengesahan: 2011,
    },
    {
      foto: "ELISA",
      nama: "Elisa",
      nomor: "20101321752",
      tempat_tanggal_lahir: "Ulak Pianggu, 13 Juni 1995",
      domisili: "Ulak Pianggu",
      kontak: null,
      pengesahan: 2011,
    },
    {
      foto: "ERIK SANDELA",
      nama: "Erik Sandela",
      nomor: null,
      tempat_tanggal_lahir: "Ulak Pianggu, 05 Desember 1994",
      domisili: "Ulak Pianggu",
      kontak: "0895418359977",
      pengesahan: 2011,
    },
    {
      foto: "RIANSYAH",
      nama: "Riansyah",
      nomor: null,
      tempat_tanggal_lahir: "Pulau Borang, 21 November 1992",
      domisili: "Serdang Menang",
      kontak: null,
      pengesahan: 2011,
    },
    {
      foto: "LAMUDIN",
      nama: "Lamudin",
      nomor: "20101321757",
      tempat_tanggal_lahir: "Serdang Menang, 17 Juli 1995",
      domisili: "Serdang Menang",
      kontak: "081367460157",
      pengesahan: 2011,
    },
    {
      foto: "EVAN FARKA",
      nama: "Evan Farka",
      nomor: "20101321750",
      tempat_tanggal_lahir: "Berkat, 05 Juli 1994",
      domisili: "Berkat",
      kontak: "082269693653",
      pengesahan: 2011,
    },
    {
      foto: "ABDUL MULUK",
      nama: "Abdul Muluk",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: "Ulak Pianggu",
      kontak: "082278009306",
      pengesahan: 2011,
    },
    {
      foto: "GUSMAN",
      nama: "Gusman",
      nomor: null,
      tempat_tanggal_lahir: "Serdang Menang, 25 Desember 1992",
      domisili: "Keman",
      kontak: "082279202785",
      pengesahan: 2011,
    },
    {
      foto: "SAF AGUSMIA",
      nama: "Saf Agusmia",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: "Ulak Pianggu",
      kontak: null,
      pengesahan: 2011,
    },
    {
      foto: "SYAHRIL SIDIK",
      nama: "Syahril Sidik",
      nomor: null,
      tempat_tanggal_lahir: "8 Februari 1994",
      domisili: "Terate",
      kontak: null,
      pengesahan: 2011,
    },
  ],

  // Tambahan Batch 5 - Pengesahan 2012
  2012: [
    {
      foto: "ADE PUTRI GAYATRI",
      nama: "Ade Putri Gayatri",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: "Pulau Betung",
      kontak: null,
      pengesahan: 2012,
    },
    {
      foto: "ADE PARADELA",
      nama: "Ade Paradela",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: "Pampangan",
      kontak: null,
      pengesahan: 2012,
    },
    {
      foto: "KUSNAIDI",
      nama: "Kusnaidi",
      nomor: "20101322275",
      tempat_tanggal_lahir: "Keman, 27 November 1993",
      domisili: "Keman Baru",
      kontak: "082278983228",
      pengesahan: 2012,
    },
    {
      foto: "SOMAD",
      nama: "Somad",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: "Keman",
      kontak: null,
      pengesahan: 2012,
    },
    {
      foto: "PAWIRAN",
      nama: "Pawiran",
      nomor: null,
      tempat_tanggal_lahir: "Kandis, 25 Desember 1995",
      domisili: "Kandis",
      kontak: null,
      pengesahan: 2012,
    },
    {
      foto: "JERI RANGKUTI",
      nama: "Jeri Rangkuti",
      nomor: "20101322276",
      tempat_tanggal_lahir: "Keman, 19 Mei 1995",
      domisili: "Keman Baru",
      kontak: "082371968195",
      pengesahan: 2012,
    },
    {
      foto: "LELITA MARIZI",
      nama: "Lelita Marizi",
      nomor: "20101322297",
      tempat_tanggal_lahir: "Bungin Tinggi, 08 Maret 1997",
      domisili: "Bungin Tinggi",
      kontak: "085269857007",
      pengesahan: 2012,
    },
    {
      foto: "ROMANI",
      nama: "Romani",
      nomor: "20101322270",
      tempat_tanggal_lahir: "Ulak Pianggu, 04 Juli 1994",
      domisili: "Ulak Pianggu",
      kontak: null,
      pengesahan: 2012,
    },
    {
      foto: "MISKA",
      nama: "Miska",
      nomor: "20101322274",
      tempat_tanggal_lahir: "Pulau Layang, 27 Oktober 1994",
      domisili: "Pulau Layang",
      kontak: null,
      pengesahan: 2012,
    },
    {
      foto: "RHAFELDO EKA PUTRA",
      nama: "Rhafeldo Eka Putra",
      nomor: "20101322286",
      tempat_tanggal_lahir: "Berkat, 10 Maret 1996",
      domisili: "Berkat",
      kontak: "085266424602",
      pengesahan: 2012,
    },
    {
      foto: "ANDRI ALBERTO",
      nama: "Andri Alberto",
      nomor: "20101322293",
      tempat_tanggal_lahir: "Kayuagung, 15 November 1995",
      domisili: "Terate",
      kontak: "082253031740",
      pengesahan: 2012,
    },
    {
      foto: "BENNY ANGGRIAWAN",
      nama: "Benny Anggriawan",
      nomor: "20101322295",
      tempat_tanggal_lahir: "Plaju, 11 Februari 1994",
      domisili: "Terate",
      kontak: null,
      pengesahan: 2012,
    },
    {
      foto: "REVEL DEVSING HILINDER",
      nama: "Revel Devsing Hilinder",
      nomor: "20101322284",
      tempat_tanggal_lahir: "Berkat, 13 Mei 1995",
      domisili: "Berkat",
      kontak: "082288518374",
      pengesahan: 2012,
    },
    {
      foto: "ASRUN",
      nama: "Asrun",
      nomor: "20101322287",
      tempat_tanggal_lahir: "Sukaraja, 25 Maret 1995",
      domisili: "Sukaraja",
      kontak: "085609647395",
      pengesahan: 2012,
    },
    {
      foto: "HAPRIL TRIADI",
      nama: "Hapril Triadi",
      nomor: "20101322279",
      tempat_tanggal_lahir: "Pampangan, 11 April 1996",
      domisili: "Pampangan",
      kontak: "087734429264",
      pengesahan: 2012,
    },
    {
      foto: "BONI CANDRA",
      nama: "Boni Candra",
      nomor: "20101322277",
      tempat_tanggal_lahir: "Sri Menang, 15 April 1996",
      domisili: "Sri Menang",
      kontak: null,
      pengesahan: 2012,
    },
    {
      foto: "GERRY ADE SOECIPTO",
      nama: "Gerry Ade Soecipto",
      nomor: "20101322296",
      tempat_tanggal_lahir: "Terate, 19 Juni 1997",
      domisili: "Terate",
      kontak: "085758822214",
      pengesahan: 2012,
    },
    {
      foto: "GELLA ARINDA",
      nama: "Gella Arinda",
      nomor: "20101322280",
      tempat_tanggal_lahir: "Penyandingan, 16 November 1997",
      domisili: "Penyandingan",
      kontak: "082387430240",
      pengesahan: 2012,
    },
    {
      foto: "RESINTA RAHMAYANI",
      nama: "Resinta Rahmayani",
      nomor: "20101322292",
      tempat_tanggal_lahir: "Terate, 3 Juli 1996",
      domisili: "Serdang Menang",
      kontak: null,
      pengesahan: 2012,
    },
    {
      foto: "ZELIKA MEISITA",
      nama: "Zelika Meisita",
      nomor: "20101322289",
      tempat_tanggal_lahir: "Palembang, 20 Mei 1996",
      domisili: "Serdang Menang",
      kontak: "085219196557",
      pengesahan: 2012,
    },
    {
      foto: "ANISA FITRI",
      nama: "Anisa Fitri",
      nomor: "20101322290",
      tempat_tanggal_lahir: "Terusan Menang, 02 September 1996",
      domisili: "Terusan Menang",
      kontak: null,
      pengesahan: 2012,
    },
    {
      foto: "PUTRI WULANSARI",
      nama: "Putri Wulansari",
      nomor: "20101322294",
      tempat_tanggal_lahir: "Serdang Menang, 31 Desember 1995",
      domisili: "Serdang Menang",
      kontak: "0895637333467",
      pengesahan: 2012,
    },
    {
      foto: "DANIL RISALDI",
      nama: "Danil Risaldi",
      nomor: "20101322285",
      tempat_tanggal_lahir: "Berkat, 17 April 1995",
      domisili: "Berkat",
      kontak: "082280110841",
      pengesahan: 2012,
    },
    {
      foto: "FIKTOR KARENO",
      nama: "Fiktor Kareno",
      nomor: "20101322283",
      tempat_tanggal_lahir: "Berkat, 29 Juli 1995",
      domisili: "Berkat",
      kontak: null,
      pengesahan: 2012,
    },
    {
      foto: "ABDUL ROHIM",
      nama: "Abdul Rohim",
      nomor: "20101322298",
      tempat_tanggal_lahir: "Palembang, 13 Juli 1997",
      domisili: "Sp. Padang",
      kontak: null,
      pengesahan: 2012,
    },
    {
      foto: "WANDRA",
      nama: "Wandra",
      nomor: "20101322282",
      tempat_tanggal_lahir: "Sukaraja, 15 Juli 1992",
      domisili: "Sukaraja",
      kontak: "082182165435",
      pengesahan: 2012,
    },
    {
      foto: "SELIANA JUNITA",
      nama: "Seliana Junita",
      nomor: "20101322281",
      tempat_tanggal_lahir: "Palembang, 13 Juni 1997",
      domisili: "Sp. Padang",
      kontak: "082183937960",
      pengesahan: 2012,
    },
    {
      foto: "DEBI NOVALIA",
      nama: "Debi Novalia",
      nomor: "20101322281",
      tempat_tanggal_lahir: "Serdang Menang, 04 November 1997",
      domisili: "Serdang Menang",
      kontak: "08999994565",
      pengesahan: 2012,
    },
    {
      foto: "YELIS",
      nama: "Yelis",
      nomor: "20101322288",
      tempat_tanggal_lahir: "Terate, 19 April 1995",
      domisili: "Terate",
      kontak: null,
      pengesahan: 2012,
    },
    {
      foto: "IKEK PRATIWI",
      nama: "Ikek Pratiwi",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: "Terusan Menang",
      kontak: null,
      pengesahan: 2012,
    },
  ],

  // Tambahan Batch 6 - Pengesahan 2013
  2013: [
    {
      foto: "RISYAR APRIANTAMA",
      nama: "Risyar Apriantama",
      nomor: "20131320786",
      tempat_tanggal_lahir: "Terate, 13 April 1998",
      domisili: "Terate",
      kontak: null,
      pengesahan: 2013,
    },
  ],

  // Tambahan Batch 7 - Pengesahan 2014
  2014: [
    {
      foto: "APRIANSYAH",
      nama: "Apriansyah",
      nomor: "20141321619",
      tempat_tanggal_lahir: "Riding, 17 November 1998",
      domisili: "Sepang",
      kontak: "082178727835",
      pengesahan: 2014,
    },
    {
      foto: "REZA APRIADI",
      nama: "Reza Apriadi",
      nomor: "20141321625",
      tempat_tanggal_lahir: "Bogor, 30 April 1998",
      domisili: "Pampangan",
      kontak: "087730927006",
      pengesahan: 2014,
    },
    {
      foto: "RIYAN HIDAYAT",
      nama: "Riyan Hidayat",
      nomor: "20141321630",
      tempat_tanggal_lahir: "Selat Ajaran, 04 Juni 1997",
      domisili: "Sukaraja",
      kontak: "081287852714",
      pengesahan: 2014,
    },
    {
      foto: "SEPRIANSYAH",
      nama: "Sepriansyah",
      nomor: "20141321632",
      tempat_tanggal_lahir: "Sukaraja, 16 September 1997",
      domisili: "Terusan Menang",
      kontak: null,
      pengesahan: 2014,
    },
    {
      foto: "JERI",
      nama: "Jeri",
      nomor: "20141321622",
      tempat_tanggal_lahir: "Keman, 14 Juli 1996",
      domisili: "Keman",
      kontak: "082186647328",
      pengesahan: 2014,
    },
    {
      foto: "DICKI RAMADHAN",
      nama: "Dicki Ramadhan",
      nomor: null,
      tempat_tanggal_lahir: "Sepang, 12 Januari 1997",
      domisili: "Sepang",
      kontak: null,
      pengesahan: 2014,
    },
    {
      foto: "SARWIN",
      nama: "Sarwin",
      nomor: "20141321626",
      tempat_tanggal_lahir: "Keman, 30 Juni 1998",
      domisili: "Keman Baru",
      kontak: null,
      pengesahan: 2014,
    },
    {
      foto: "M. ARI NUGRAHA",
      nama: "M. Ari Nugraha",
      nomor: "20141321611",
      tempat_tanggal_lahir: "Prabumulih, 07 Februari 1998",
      domisili: "Pampangan",
      kontak: "082279131116",
      pengesahan: 2014,
    },
    {
      foto: "M. FAHMI",
      nama: "M. Fahmi",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: "Sri Menang",
      kontak: null,
      pengesahan: 2014,
    },
    {
      foto: "TUNGKI ARIWIBOWO",
      nama: "Tungki Ariwibowo",
      nomor: "20141321627",
      tempat_tanggal_lahir: "Ulak Pianggu, 23 Juli 1997",
      domisili: "Pulau Betung",
      kontak: null,
      pengesahan: 2014,
    },
    {
      foto: "ABDUL RONI",
      nama: "Abdul Roni",
      nomor: "20141321618",
      tempat_tanggal_lahir: "Palembang, 06 September 1997",
      domisili: "Sepang",
      kontak: null,
      pengesahan: 2014,
    },
    {
      foto: "DANDI SAPUTRA",
      nama: "Dandi Saputra",
      nomor: "20141321620",
      tempat_tanggal_lahir: "Pampangan, 01 November 1997",
      domisili: "Pampangan",
      kontak: null,
      pengesahan: 2014,
    },
    {
      foto: "RIZKI AMELIANI",
      nama: "Rizki Ameliani",
      nomor: "20141321631",
      tempat_tanggal_lahir: "Terate, 17 Mei 1991",
      domisili: "Terate",
      kontak: null,
      pengesahan: 2014,
    },
    {
      foto: "ADDRIANIE NOVELLIE",
      nama: "Addrianie Novellie",
      nomor: "20141321628",
      tempat_tanggal_lahir: "Terate, 05 Desember 1994",
      domisili: "Terate",
      kontak: "082186504252",
      pengesahan: 2014,
    },
    {
      foto: "DEWI SURYATI",
      nama: "Dewi Suryati",
      nomor: null,
      tempat_tanggal_lahir: "Terusan Menang, 06 Februari 1998",
      domisili: "Terusan Menang",
      kontak: "082279202785",
      pengesahan: 2014,
    },
  ],

  // Tambahan Batch 8 - Pengesahan 2015
  2015: [
    {
      foto: "ROSMALINDA",
      nama: "Rosmalinda",
      nomor: "20151320628",
      tempat_tanggal_lahir: "Terate, 27 Oktober 1996",
      domisili: "Terate",
      kontak: "089604854783",
      pengesahan: 2015,
    },
    {
      foto: "SELESTE",
      nama: "Seleste",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: "Berkat",
      kontak: null,
      pengesahan: 2015,
    },
    {
      foto: "SULISTIONO AKBAR",
      nama: "Sulistiono Akbar",
      nomor: "20151320630",
      tempat_tanggal_lahir: "Sp. Padang, 23 April 1999",
      domisili: "Sp. Padang",
      kontak: "08973985602",
      pengesahan: 2015,
    },
    {
      foto: "MOH RIZAL",
      nama: "Moh Rizal",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: "Terate",
      kontak: "081274657509",
      pengesahan: 2015,
    },
  ],

  // Tambahan Batch 9 - Pengesahan 2016
  2016: [
    {
      foto: "BELLA RAHMADINA",
      nama: "Bella Rahmadina",
      nomor: "20161320763",
      tempat_tanggal_lahir: "Terusan Menang, 06 Maret 2000",
      domisili: "Terusan Menang",
      kontak: "087720991000",
      pengesahan: 2016,
    },
    {
      foto: "APERO",
      nama: "Apero",
      nomor: "20161320759",
      tempat_tanggal_lahir: "Sukaraja, 03 September 1999",
      domisili: "Sukaraja",
      kontak: "085920365778",
      pengesahan: 2016,
    },
    {
      foto: "MUHAMMAD DANIL",
      nama: "Muhammad Danil",
      nomor: "20161320783",
      tempat_tanggal_lahir: "Palembang, 13 September 1998",
      domisili: "Penyandingan",
      kontak: "087897153507",
      pengesahan: 2016,
    },
    {
      foto: "GEVIN MAHESTU",
      nama: "Gevin Mahestu",
      nomor: null,
      tempat_tanggal_lahir: "Awal Terusan, 05 Mei 1999",
      domisili: "Awal Terusan",
      kontak: "082282285331",
      pengesahan: 2016,
    },
    {
      foto: "AYU NARISKI",
      nama: "Ayu Nariski",
      nomor: "20161320762",
      tempat_tanggal_lahir: "Awal Terusan, 05 Februari 1998",
      domisili: "Awal Terusan",
      kontak: "085377467153",
      pengesahan: 2016,
    },
    {
      foto: "MARDIANA",
      nama: "Mardiana",
      nomor: null,
      tempat_tanggal_lahir: "Awal Terusan, 05 Oktober 2000",
      domisili: "Awal Terusan",
      kontak: "0895620303144",
      pengesahan: 2016,
    },
    {
      foto: "CITRA DEWI",
      nama: "Citra Dewi",
      nomor: "201613200139",
      tempat_tanggal_lahir: "Mangun Jaya, 29 Oktober 1998",
      domisili: "Pulu Beruang",
      kontak: "081279549447",
      pengesahan: 2016,
    },
    {
      foto: "YUNIARTI",
      nama: "Yuniarti",
      nomor: "20161320801",
      tempat_tanggal_lahir: "Awal Terusan, 14 Agustus 1999",
      domisili: "Awal Terusan",
      kontak: null,
      pengesahan: 2016,
    },
    {
      foto: "EMILIA TABSAH",
      nama: "Emilia Tabsah",
      nomor: null,
      tempat_tanggal_lahir: "Kijang Ulu, 12 Desember 1999",
      domisili: "Kijang Ulu",
      kontak: null,
      pengesahan: 2016,
    },
    {
      foto: "DESI RATNASARI",
      nama: "Desi Ratnasari",
      nomor: null,
      tempat_tanggal_lahir: "Tebing Tinggi, 03 Oktober 1999",
      domisili: "Pematang Buluran",
      kontak: null,
      pengesahan: 2016,
    },
    {
      foto: "RAHAYU",
      nama: "Rahayu",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: "Tanjung Alai",
      kontak: null,
      pengesahan: 2016,
    },
    {
      foto: "RINALDI",
      nama: "Rinaldi",
      nomor: null,
      tempat_tanggal_lahir: "Awal Terusan, 07 Oktober 1999",
      domisili: "Awal Terusan",
      kontak: null,
      pengesahan: 2016,
    },
    {
      foto: "ABDAR RA’UF",
      nama: "Abdar Ra’uf",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: "Pematang Buluran",
      kontak: null,
      pengesahan: 2016,
    },
    {
      foto: "ARIFA’I",
      nama: "Arifa’i",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: "Tanjung Serang",
      kontak: null,
      pengesahan: 2016,
    },
    {
      foto: "M RICO JUARDA",
      nama: "M. Rico Juarda",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: "Teloko",
      kontak: null,
      pengesahan: 2016,
    },
  ],

  // Tambahan Batch 10 - Pengesahan 2017
  2017: [
    {
      foto: "TAUPAN EKO NUGRAHA",
      nama: "Taupan Eko Nugraha",
      nomor: "20171320836",
      tempat_tanggal_lahir: "Terate, 10 April 1999",
      domisili: "Terate",
      kontak: "081278448812",
      pengesahan: 2017,
    },
    {
      foto: "FEBRI YANSAH",
      nama: "Febri Yansah",
      nomor: "20171320830",
      tempat_tanggal_lahir: "Palembang, 19 Februari 2001",
      domisili: "Penyandingan",
      kontak: "087895738664",
      pengesahan: 2017,
    },
    {
      foto: "ALVIANSYAH",
      nama: "Alviansyah",
      nomor: "20171320826",
      tempat_tanggal_lahir: "Terusan Menang, 28 Mei 2001",
      domisili: "Terusan Menang",
      kontak: "088269353472",
      pengesahan: 2017,
    },
    {
      foto: "M. FANTRA ROMADHON",
      nama: "M. Fantra Romadhon",
      nomor: null,
      tempat_tanggal_lahir: "Terusan Menang, 09 Desember 2000",
      domisili: "Terusan Menang",
      kontak: "082380147690",
      pengesahan: 2017,
    },
    {
      foto: "JONI AKBAR",
      nama: "Joni Akbar",
      nomor: null,
      tempat_tanggal_lahir: "Sepang, 05 Juni 2000",
      domisili: "Berkat",
      kontak: "082281797867",
      pengesahan: 2017,
    },
    {
      foto: "AGUS SALIM",
      nama: "Agus Salim",
      nomor: null,
      tempat_tanggal_lahir: "Belanti, 06 Agustus 2000",
      domisili: "Belanti",
      kontak: "081367496061",
      pengesahan: 2017,
    },
    {
      foto: "ARMAN",
      nama: "Arman",
      nomor: "20171320828",
      tempat_tanggal_lahir: "Awal Terusan, 15 Mei 2001",
      domisili: "Awal Terusan",
      kontak: "08896652990",
      pengesahan: 2017,
    },
    {
      foto: "SYALILA WIDYAN FAHIRA",
      nama: "Syalila Widyan Fahira",
      nomor: null,
      tempat_tanggal_lahir: "Jakarta, 11 Januari 2003",
      domisili: "Terate",
      kontak: "081992008772",
      pengesahan: 2017,
    },
    {
      foto: "ANISA MAYANG SARI",
      nama: "Anisa Mayang Sari",
      nomor: null,
      tempat_tanggal_lahir: "Terate, 29 Juli 2002",
      domisili: "Terate",
      kontak: "088286469505",
      pengesahan: 2017,
    },
    {
      foto: "AUDI YESYAH AULIA",
      nama: "Audi Yesyah Aulia",
      nomor: null,
      tempat_tanggal_lahir: "Terate, 23 April 2003",
      domisili: "Terate",
      kontak: "087869658400",
      pengesahan: 2017,
    },
    {
      foto: "SRI WINDA NINGSIH",
      nama: "Sri Winda Ningsih",
      nomor: null,
      tempat_tanggal_lahir: "Terate, 29 September 2001",
      domisili: "Terusan Menang",
      kontak: "081273223202",
      pengesahan: 2017,
    },
    {
      foto: "ZAKIA AZZAHRA",
      nama: "Zakia Azzahra",
      nomor: null,
      tempat_tanggal_lahir: "Terate, 29 Oktober 2000",
      domisili: "Terate",
      kontak: "082374337391",
      pengesahan: 2017,
    },
    {
      foto: "PINGKI",
      nama: "Pingki",
      nomor: null,
      tempat_tanggal_lahir: "Sukaraja, 29 Maret 2001",
      domisili: "Sukaraja",
      kontak: "082192818044",
      pengesahan: 2017,
    },
    {
      foto: "JAKA PRATAMA",
      nama: "Jaka Pratama",
      nomor: "20171320838",
      tempat_tanggal_lahir: "Awal Terusan, 23 Desember 2000",
      domisili: "Awal Terusan",
      kontak: null,
      pengesahan: 2017,
    },
    {
      foto: "KOMARUDIN",
      nama: "Komarudin",
      nomor: null,
      tempat_tanggal_lahir: "Awal Terusan, 31 Mei 2000",
      domisili: "Pematang Buluran",
      kontak: "083187711144",
      pengesahan: 2017,
    },
    {
      foto: "YUPRIZER",
      nama: "Yuprizer",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: null,
      kontak: null,
      pengesahan: 2017,
    },
    {
      foto: "RISKIKA RUCITRA",
      nama: "Riskika Rucitra",
      nomor: null,
      tempat_tanggal_lahir: "Awal Terusan, 14 Mei 2003",
      domisili: "Awal Terusan",
      kontak: "089526593955",
      pengesahan: 2017,
    },
    {
      foto: "OKTA KIRANTI",
      nama: "Okta Kiranti",
      nomor: null,
      tempat_tanggal_lahir: "Awal Terusan, 07 Oktober 2002",
      domisili: "Awal Terusan",
      kontak: "083836895280",
      pengesahan: 2017,
    },
    {
      foto: "JERI YANTO",
      nama: "Jeri Yanto",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: "Pematang Buluran",
      kontak: null,
      pengesahan: 2017,
    },
  ],

  // Tambahan Batch 11 - Pengesahan 2018
  2018: [
    {
      foto: "MUHAMMAD ROLIANSYAH",
      nama: "Muhammad Roliansyah",
      nomor: null,
      tempat_tanggal_lahir: "Ulak Kemang Baru, 05 April 2001",
      domisili: "Ulak Kemang Baru",
      kontak: "083121268156",
      pengesahan: 2018,
    },
    {
      foto: "CANDRA",
      nama: "Candra",
      nomor: null,
      tempat_tanggal_lahir: "Ulak Kemang, 27 Desember 2001",
      domisili: "Ulak Kemang",
      kontak: "081995324135",
      pengesahan: 2018,
    },
    {
      foto: "HAMIM RASYID RIDHO",
      nama: "Hamim Rasyid Ridho",
      nomor: "201813212403",
      tempat_tanggal_lahir: "Terate, 28 Januari 2002",
      domisili: "Terate",
      kontak: "081273959192",
      pengesahan: 2018,
    },
    {
      foto: "M. ROBI EKA PUTRA",
      nama: "M. Robi Eka Putra",
      nomor: "201813212404",
      tempat_tanggal_lahir: "Palembang, 27 Juli 2000",
      domisili: "Berkat",
      kontak: "085257530129",
      pengesahan: 2018,
    },
    {
      foto: "JECKY ZIMAH",
      nama: "Jecky Zimah",
      nomor: "201813212405",
      tempat_tanggal_lahir: "Berkat, 13 Agustus 2000",
      domisili: "Berkat",
      kontak: "085263743302",
      pengesahan: 2018,
    },
    {
      foto: "TANIA",
      nama: "Tania",
      nomor: "19720010009",
      tempat_tanggal_lahir: "Terusan Menang, 05 Desember 2003",
      domisili: "Terusan Menang",
      kontak: "087878232010",
      pengesahan: 2018,
    },
    {
      foto: "BASTONI",
      nama: "Bastoni",
      nomor: "201813212408",
      tempat_tanggal_lahir: "Kayuagung, 17 Mei 2001",
      domisili: "Penyandingan",
      kontak: "087893743855",
      pengesahan: 2018,
    },
    {
      foto: "SUPRAPTO",
      nama: "Suprapto",
      nomor: "201813212410",
      tempat_tanggal_lahir: "Berkat, 23 November 2001",
      domisili: "Berkat",
      kontak: "085362891534",
      pengesahan: 2018,
    },
    {
      foto: "TRELI",
      nama: "Treli",
      nomor: null,
      tempat_tanggal_lahir: "Penyandingan, 09 Januari 2002",
      domisili: "Penyandingan",
      kontak: null,
      pengesahan: 2018,
    },
  ],

  // Tambahan Batch 12 - Pengesahan 2019
  2019: [
    {
      foto: "MUHAMAD FIRLI",
      nama: "Muhamad Firli",
      nomor: "201913235561",
      tempat_tanggal_lahir: "Berkat, 22 April 2003",
      domisili: "Berkat",
      kontak: "081271745906",
      pengesahan: 2019,
    },
    {
      foto: "ELTRI ROREN NOPRENKA",
      nama: "Eltri Roren Noprenka",
      nomor: "201913235556",
      tempat_tanggal_lahir: "Kayuagung, 04 Desember 2003",
      domisili: "Serdang Menang",
      kontak: "088286361000",
      pengesahan: 2019,
    },
    {
      foto: "RUSYAN HASRAT",
      nama: "Rusyan Hasrat",
      nomor: "201913235567",
      tempat_tanggal_lahir: "Kayuagung, 23 Desember 2000",
      domisili: "Terusan Menang",
      kontak: "082319456478",
      pengesahan: 2019,
    },
    {
      foto: "LILIANI",
      nama: "Liliani",
      nomor: "2019132235559",
      tempat_tanggal_lahir: "Berkat, 04 Oktober 2001",
      domisili: "Berkat",
      kontak: "081929223197",
      pengesahan: 2019,
    },
    {
      foto: "SARMILA",
      nama: "Sarmila",
      nomor: "2019132235568",
      tempat_tanggal_lahir: "Terusan Menang, 07 Januari 2002",
      domisili: "Terusan Menang",
      kontak: "083102756871",
      pengesahan: 2019,
    },
    {
      foto: "BAINA",
      nama: "Baina",
      nomor: "2019132235554",
      tempat_tanggal_lahir: "Sukaraja, 01 Januari 2000",
      domisili: "Sukaraja",
      kontak: "088268371985",
      pengesahan: 2019,
    },
    {
      foto: "ERINA",
      nama: "Erina",
      nomor: "2019132235557",
      tempat_tanggal_lahir: "Ulak Kemang, 25 November 2000",
      domisili: "Ulak Kemang",
      kontak: "085807442408",
      pengesahan: 2019,
    },
    {
      foto: "ANDRE GUSTIADI",
      nama: "Andre Gustiadi",
      nomor: "20191322355..",
      tempat_tanggal_lahir: null,
      domisili: null,
      kontak: null,
      pengesahan: 2019,
    },
    {
      foto: "NURLAILA",
      nama: "Nurlaila",
      nomor: "2019132235563",
      tempat_tanggal_lahir: "Kayuagung, 19 November 2001",
      domisili: "Belanti",
      kontak: "082138658442",
      pengesahan: 2019,
    },
    {
      foto: "SISKA AMELIA",
      nama: "Siska Amelia",
      nomor: "20191322355..",
      tempat_tanggal_lahir: "Bubusan, 24 Juli 2002",
      domisili: "Bubusan",
      kontak: "083113083964",
      pengesahan: 2019,
    },
    {
      foto: "RENALDO",
      nama: "Renaldo",
      nomor: "20191322355..",
      tempat_tanggal_lahir: null,
      domisili: "Terate",
      kontak: "082378504378",
      pengesahan: 2019,
    },
    {
      foto: "M ALFIN ASRI",
      nama: "M. Alfin Asri",
      nomor: "2019132235560",
      tempat_tanggal_lahir: "Palembang, 27 September 2000",
      domisili: "Terate",
      kontak: "085279726492",
      pengesahan: 2019,
    },
    {
      foto: "RENIA ANGGITA",
      nama: "Renia Anggita",
      nomor: "20191322355..",
      tempat_tanggal_lahir: "16 April 2002",
      domisili: "Terusan Menang",
      kontak: "087813575450",
      pengesahan: 2019,
    },
    {
      foto: "LILIA",
      nama: "Lilia",
      nomor: "20191322355..",
      tempat_tanggal_lahir: null,
      domisili: "Terate",
      kontak: "085227908676",
      pengesahan: 2019,
    },
    {
      foto: "UMMI KALSUM",
      nama: "Ummi Kalsum",
      nomor: "20191322355..",
      tempat_tanggal_lahir: "Terate, 18 Juli 2003",
      domisili: "Terate",
      kontak: "088286578622",
      pengesahan: 2019,
    },
    {
      foto: "RINDIANI",
      nama: "Rindiani",
      nomor: "20191322355..",
      tempat_tanggal_lahir: "2 September 2000",
      domisili: "Bungin Tinggi",
      kontak: null,
      pengesahan: 2019,
    },
    {
      foto: "MUHAMMAD FRANSISCO",
      nama: "Muhammad Fransisco",
      nomor: "20191322355..",
      tempat_tanggal_lahir: "Sepang, 09 Mei 2001",
      domisili: "Sepang",
      kontak: null,
      pengesahan: 2019,
    },
    {
      foto: "EDI SAPUTRA",
      nama: "Edi Saputra",
      nomor: "20191322355..",
      tempat_tanggal_lahir: "10 November 2000",
      domisili: "Sukaraja",
      kontak: null,
      pengesahan: 2019,
    },
  ],

  // Tambahan Batch 13 - Pengesahan 2020
  2020: [
    {
      foto: "SUBANDRIO",
      nama: "Subandrio",
      nomor: "202013244917",
      tempat_tanggal_lahir: "Talang Cempedak, 09 Maret 2002",
      domisili: "Pematang Gaib",
      kontak: "08386041346",
      pengesahan: 2020,
    },
    {
      foto: "MIRA APRILIA",
      nama: "Mira Aprilia",
      nomor: "202013244918",
      tempat_tanggal_lahir: "Terate, 11 April 2004",
      domisili: "Terate",
      kontak: "081997395686",
      pengesahan: 2020,
    },
    {
      foto: "YUDA APENDI",
      nama: "Yuda Apendi",
      nomor: "202013244921",
      tempat_tanggal_lahir: "Sujian, 25 Mei 2002",
      domisili: "Pematang Gaib",
      kontak: "082180861209",
      pengesahan: 2020,
    },
    {
      foto: "DIMAS",
      nama: "Dimas",
      nomor: "202013244920",
      tempat_tanggal_lahir: "Kayuagung, 26 Juni 2004",
      domisili: "Penyandingan",
      kontak: "08291853474",
      pengesahan: 2020,
    },
    {
      foto: "RENOL SUBAKTI",
      nama: "Renol Subakti",
      nomor: "202013244919",
      tempat_tanggal_lahir: "22 Februari 2002",
      domisili: "Berkat",
      kontak: null,
      pengesahan: 2020,
    },
  ],

  // Tambahan Batch 14 - Pengesahan 2022
  2022: [
    {
      foto: "AYU WANDIRA",
      nama: "Ayu Wandira",
      nomor: "202213252460",
      tempat_tanggal_lahir: "Terusan Menang, 31 Mei 2005",
      domisili: "Terusan Menang",
      kontak: "081216651794",
      pengesahan: 2022,
    },
    {
      foto: "DHIMAS DWIJAYA PUTRA",
      nama: "Dhimas Dwijaya Putra",
      nomor: "2022132524..",
      tempat_tanggal_lahir: "Palembang, 20 Desember 2004",
      domisili: "Berkat",
      kontak: "083871503740",
      pengesahan: 2022,
    },
    {
      foto: "BAYU GUSTIYAN",
      nama: "Bayu Gustiyan",
      nomor: "202213252461",
      tempat_tanggal_lahir: "Berkat, 26 Agustus 2006",
      domisili: "Penyandingan",
      kontak: "083173595937",
      pengesahan: 2022,
    },
    {
      foto: "ILHAM",
      nama: "Ilham",
      nomor: "202213252464",
      tempat_tanggal_lahir: "Ulak Kemang, 06 September 2006",
      domisili: "Ulak Kemang",
      kontak: "088274367964",
      pengesahan: 2022,
    },
    {
      foto: "SRI DWI LESTARI",
      nama: "Sri Dwi Lestari",
      nomor: "202213252470",
      tempat_tanggal_lahir: "Terate, 26 Maret 2007",
      domisili: "Terusan Menang",
      kontak: "083834339744",
      pengesahan: 2022,
    },
    {
      foto: "PRAMANA",
      nama: "Pramana",
      nomor: "2022132524..",
      tempat_tanggal_lahir: "Ulak Kemang, 24 Juli 2002",
      domisili: "Ulak Kemang",
      kontak: "0895420972325",
      pengesahan: 2022,
    },
    {
      foto: "DESI KARTIKA",
      nama: "Desi Kartika",
      nomor: "202213252462",
      tempat_tanggal_lahir: "Serdang Menang, 18 Desember 2005",
      domisili: "Serdang Menang",
      kontak: "083802701174",
      pengesahan: 2022,
    },
    {
      foto: "KARISMA MALHOTRA",
      nama: "Karisma Malhotra",
      nomor: "202213252465",
      tempat_tanggal_lahir: "Penyandingan, 11 Juni 2005",
      domisili: "Penyandingan",
      kontak: "083131507550",
      pengesahan: 2022,
    },
    {
      foto: "NADIA PUTRI HENSI",
      nama: "Nadia Putri Hensi",
      nomor: "202213252467",
      tempat_tanggal_lahir: "Penyandingan, 21 November 2007",
      domisili: "Penyandingan",
      kontak: "081274930561",
      pengesahan: 2022,
    },
    {
      foto: "SITI ROHANA",
      nama: "Siti Rohana",
      nomor: "2022132524..",
      tempat_tanggal_lahir: null,
      domisili: "Penyandingan",
      kontak: null,
      pengesahan: 2022,
    },
    {
      foto: "TEGAR NAGARETA",
      nama: "Tegar Nagareta",
      nomor: "2022132252471",
      tempat_tanggal_lahir: "Terusan Menang, 15 Maret 2006",
      domisili: "Bungin Tinggi",
      kontak: "088747954889",
      pengesahan: 2022,
    },
    {
      foto: "ARUM SARI",
      nama: "Arum Sari",
      nomor: "2022132252459",
      tempat_tanggal_lahir: "Bungin Tinggi, 29 Agustus 2007",
      domisili: "Bungin Tinggi",
      kontak: "083159143603",
      pengesahan: 2022,
    },
    {
      foto: "M AFLA TEGAR SABRINO",
      nama: "M Afla Tegar Sabrino",
      nomor: "20221322524..",
      tempat_tanggal_lahir: null,
      domisili: null,
      kontak: null,
      pengesahan: 2022,
    },
  ],

  // Tambahan Batch 15 - Pengesahan 2023
  2023: [
    {
      foto: "META",
      nama: "Meta",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: "Awal Terusan",
      kontak: null,
      pengesahan: 2023,
    },
    {
      foto: "IRMA",
      nama: "Irma",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: "Awal Terusan",
      kontak: null,
      pengesahan: 2023,
    },
    {
      foto: "M. ALMAN SUHERMAN",
      nama: "M. Alman Suherman",
      nomor: "16022023132042789",
      tempat_tanggal_lahir: "Awal Terusan, 18 November 2002",
      domisili: "Awal Terusan",
      kontak: "0895621552957",
      pengesahan: 2023,
    },
    {
      foto: "RAHMIDO",
      nama: "Rahmido",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: "Awal Terusan",
      kontak: null,
      pengesahan: 2023,
    },
    {
      foto: "ANTO SOPIANTO",
      nama: "Anto Sopianto",
      nomor: "16022023132042784",
      tempat_tanggal_lahir: "Rawang Besar, 16 Desember 2001",
      domisili: "Awal Terusan",
      kontak: "085658828362",
      pengesahan: 2023,
    },
    {
      foto: "MEMET",
      nama: "Memet",
      nomor: "16022023132042787",
      tempat_tanggal_lahir: "Awal Terusan, 02 Desember 2001",
      domisili: "Awal Terusan",
      kontak: "087868427897",
      pengesahan: 2023,
    },
    {
      foto: "ARIANSYAH",
      nama: "Ariansyah",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: null,
      kontak: null,
      pengesahan: 2023,
    },
  ],

  // Tambahan Batch 16 - Pengesahan 2024
  2024: [
    {
      foto: "KHOIRUNNISA ",
      nama: "Khoirunnisa",
      nomor: null,
      tempat_tanggal_lahir: "Terate, 04 Januari 2008",
      domisili: "Terate",
      kontak: "083173076039",
      pengesahan: 2024,
    },
    {
      foto: "NABILAH",
      nama: "Nabilah",
      nomor: null,
      tempat_tanggal_lahir: "Terusan Menang, 15 Juli 2007",
      domisili: "Terusan Menang",
      kontak: "085383963330",
      pengesahan: 2024,
    },
    {
      foto: "ROSA",
      nama: "Rosa",
      nomor: null,
      tempat_tanggal_lahir: "Sukaraja, 12 Agustus 2008",
      domisili: "Sukaraja",
      kontak: "085384714051",
      pengesahan: 2024,
    },
    {
      foto: "TANIAA",
      nama: "Tania",
      nomor: null,
      tempat_tanggal_lahir: "Terusan Menang, 01 Januari 2008",
      domisili: "Terusan Menang",
      kontak: null,
      pengesahan: 2024,
    },
    {
      foto: "WIDIA",
      nama: "Widia",
      nomor: null,
      tempat_tanggal_lahir: "Sukaraja, 31 Januari 2008",
      domisili: "Sukaraja",
      kontak: "0881025670446",
      pengesahan: 2024,
    },
    {
      foto: "WULANDARI",
      nama: "Wulandari",
      nomor: null,
      tempat_tanggal_lahir: "Sukaraja, 14 Januari 2009",
      domisili: "Sukaraja",
      kontak: "081261745080",
      pengesahan: 2024,
    },
    {
      foto: "MUHAMAT JANI",
      nama: "Muhamat Jani",
      nomor: null,
      tempat_tanggal_lahir: "Rawang Besar, 05 Desember 2007",
      domisili: "Rawang Besar",
      kontak: "085783018781",
      pengesahan: 2024,
    },
    {
      foto: "PERDI EKO PRATAMA",
      nama: "Perdi Eko Pratama",
      nomor: null,
      tempat_tanggal_lahir: "Rawang Besar, 11 Maret 2008",
      domisili: "Rawang Besar",
      kontak: "081367296423",
      pengesahan: 2024,
    },
    {
      foto: "YUNI  ERLIANA SARI",
      nama: "Yuni Erliana Sari",
      nomor: null,
      tempat_tanggal_lahir: "Kayuagung, 06 Maret 2009",
      domisili: "Kayuagung",
      kontak: "083156745389",
      pengesahan: 2024,
    },
    {
      foto: "M. FHIRLY SAPUTRA",
      nama: "M. Fhirly Saputra",
      nomor: null,
      tempat_tanggal_lahir: "Kayuagung, 13 September 2009",
      domisili: "Terusan Menang",
      kontak: "085709801535",
      pengesahan: 2024,
    },
  ],

  // Tambahan Batch 17 - Pengesahan 2025
  2025: [
    {
      foto: "DIVA KARYUNI ",
      nama: "Diva Karyuni",
      nomor: null,
      tempat_tanggal_lahir: "Serdang Menang, 20 Juni 2010",
      domisili: "Serdang Menang",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "DHEA NARA CANTIKA AGTHA",
      nama: "Dhea Nara Cantika Agtha",
      nomor: null,
      tempat_tanggal_lahir: "Gedung Agung, 19 April 2011",
      domisili: "Penyandingan",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "NADIA DESTRIANTI",
      nama: "Nadia Destrianti",
      nomor: null,
      tempat_tanggal_lahir: "Terate, 22 Desember 2009",
      domisili: "Terate",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "KLARA",
      nama: "Klara",
      nomor: null,
      tempat_tanggal_lahir: "Belanti, 28 April 2009",
      domisili: "Terusan Menang",
      kontak: null,
      pengesahan: 2025,
    },
    {
      foto: "ANGGITA",
      nama: "Anggita",
      nomor: null,
      tempat_tanggal_lahir: "Belanti, 24 Februari 2007",
      domisili: "Belanti",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "PUTRI NADIA",
      nama: "Putri Nadia",
      nomor: null,
      tempat_tanggal_lahir: "Terate, 05 Desember 2008",
      domisili: "Terusan Menang",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "PUTRI INDRIYANA",
      nama: "Putri Indriyana",
      nomor: null,
      tempat_tanggal_lahir: "Terusan Menang. OKI, 09 Januari 2009",
      domisili: "Terate",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "PUTRI AYU",
      nama: "Putri Ayu",
      nomor: null,
      tempat_tanggal_lahir: "Sukaraja, 23 Juni 2010",
      domisili: "Berkat",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "LAILATUL BALQIS",
      nama: "Lailatul Balqis",
      nomor: null,
      tempat_tanggal_lahir: null,
      domisili: "Sirah Pulau Padang",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "M. REYHAN FAHIRZA",
      nama: "M. Reyhan Fahirza",
      nomor: null,
      tempat_tanggal_lahir: "Palembang, 07 Maret 2009",
      domisili: "Terusan Menang",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "SYARIF FRIANSA",
      nama: "Syarif Friansa",
      nomor: null,
      tempat_tanggal_lahir: "Serdang Menang, 28 Mei 2008",
      domisili: "Penyandingan",
      kontak: "085709801535",
      pengesahan: 2025,
    },
    {
      foto: "MUHAMMAD IQBAL",
      nama: "Muhammad Iqbal",
      nomor: null,
      tempat_tanggal_lahir: "Terate, 29 Mei 2008",
      domisili: "Terate",
      kontak: "085709801535",
      pengesahan: 2025,
    },
    {
      foto: "ADAM MALIK ",
      nama: "Adam Malik",
      nomor: null,
      tempat_tanggal_lahir: "Terusan Menang, 12 Oktober 2009",
      domisili: "Terusan Menang",
      kontak: "0883836035072",
      pengesahan: 2025,
    },
    {
      foto: "EKO",
      nama: "Eko",
      nomor: null,
      tempat_tanggal_lahir: "Ulak Kemang, 03 Januari 2009",
      domisili: "Ulak Kemang",
      kontak: "0887798392291",
      pengesahan: 2025,
    },
    {
      foto: "MUHAMMAD DANUH",
      nama: "Muhammad Danuh",
      nomor: null,
      tempat_tanggal_lahir: "Kayuagung, 19 Maret 2009",
      domisili: "Ulak Kemang",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "SATRIA",
      nama: "Satria",
      nomor: null,
      tempat_tanggal_lahir: "Kayuagung, 20 April 2007",
      domisili: "Ulak Kemang Baru",
      kontak: null,
      pengesahan: 2025,
    },
    {
      foto: "SARI",
      nama: "Sari",
      nomor: null,
      tempat_tanggal_lahir: "Keman, 11 November 2007",
      domisili: "Keman Baru",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "DEA LAURA",
      nama: "Dea Laura",
      nomor: null,
      tempat_tanggal_lahir: "Belanti, 29 Januari 2009",
      domisili: "Keman Baru",
      kontak: "0882287671398",
      pengesahan: 2025,
    },
    {
      foto: "MELA KIRANA",
      nama: "Mela Kirana",
      nomor: null,
      tempat_tanggal_lahir: "Keman, 11 September 2008",
      domisili: "Keman Baru",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "BIMA PRATAMA",
      nama: "Bima Pratama",
      nomor: null,
      tempat_tanggal_lahir: "Ulak Kemang, 03 Mei 2006",
      domisili: "Ulak Kemang",
      kontak: "0881541113057",
      pengesahan: 2025,
    },
    {
      foto: "ALENGKA",
      nama: "Alengka",
      nomor: null,
      tempat_tanggal_lahir: "Ulak Kemang, 03 April 2008",
      domisili: "Ulak Kemang",
      kontak: "0883847786778",
      pengesahan: 2025,
    },
    {
      foto: "RISKI",
      nama: "Riski",
      nomor: null,
      tempat_tanggal_lahir: "Keman, 22 Oktober 2006",
      domisili: "Keman Baru",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "M. REZA PRATAMA",
      nama: "M. Reza Pratama",
      nomor: null,
      tempat_tanggal_lahir: "Keman Baru, 05 Desember 2009",
      domisili: "Ulak Pianggu",
      kontak: "08889298656",
      pengesahan: 2025,
    },
    {
      foto: "ALDI",
      nama: "Aldi",
      nomor: null,
      tempat_tanggal_lahir: "Keman, 22 Juni 2008",
      domisili: "Keman Baru",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "AULIA MAULANA",
      nama: "Aulia Maulana",
      nomor: null,
      tempat_tanggal_lahir: "Awal Terusan, 11 Maret 2009",
      domisili: "Awal Terusan",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "IMAM KHANAFI",
      nama: "Imam Khanafi",
      nomor: null,
      tempat_tanggal_lahir: "Tulung Agung, 12 November 1979",
      domisili: "Awal Terusan",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "YUDHI APRIADI",
      nama: "Yudhi Apriadi",
      nomor: null,
      tempat_tanggal_lahir: "Awal Terusan, 09 April 1988",
      domisili: "Awal Terusan",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "ADE MARETHA PRATAMA",
      nama: "Ade Maretha Pratama",
      nomor: null,
      tempat_tanggal_lahir: "Palembang, 07 Maret 1990",
      domisili: "Awal Terusan",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "HERMAN KONI ",
      nama: "Herman Koni",
      nomor: null,
      tempat_tanggal_lahir: "Awal Terusan, 19 November 1975",
      domisili: "Awal Terusan",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "ADDRES",
      nama: "Addres",
      nomor: null,
      tempat_tanggal_lahir: "Tanjung Alai, 31 Januari 2009",
      domisili: "Terusan Laut",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "EDO ALDINO",
      nama: "Edo Aldino",
      nomor: null,
      tempat_tanggal_lahir: "Terusan Laut, 05 Juli 2009",
      domisili: "Terusan Laut",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "Iqram Shing Alfarizi",
      nama: "Iqram Shing Alfarizi",
      nomor: null,
      tempat_tanggal_lahir: "Awal Terusan, 08 Juni 2009",
      domisili: "Awal Terusan",
      kontak: "0888214052040",
      pengesahan: 2025,
    },
    {
      foto: "sairul",
      nama: "Sairul",
      nomor: null,
      tempat_tanggal_lahir: "Tulung Udiang, 23 Agustus 2009",
      domisili: "Awal Terusan",
      kontak: "08",
      pengesahan: 2025,
    },
    {
      foto: "DEN BAGUS",
      nama: "Den Bagus",
      nomor: null,
      tempat_tanggal_lahir: "Awal Terusan, 15 Agustus 2009",
      domisili: "Awal Terusan",
      kontak: "0885788001067",
      pengesahan: 2025,
    },
  ],
};

const output = document.getElementById("output");
const defaultFoto = "foto/default.png";
const searchInput = document.getElementById("searchBox");
// fungsi render data ke halaman
function renderData(keyword = "") {
  output.innerHTML = ""; // hapus isi sebelumnya

  // Loop setiap kategori dalam data
  for (let key in biodata) {
    // Tampilkan judul (nama grup: dataPertama, dataKedua)
    // filter data berdasarkan keyword nama
    const filtered = biodata[key].filter(
      (item) =>
        `${item.nama}`.toLowerCase().includes(keyword) ||
        `${item.pengesahan}`.includes(keyword)
    );
    if (filtered.length > 0) {
      // judul grup
      // const title = document.createElement("h2");
      // title.textContent = `Pengesahan ${key}`;
      // output.appendChild(title);

      // isi data
      filtered.forEach((item) => {
        const card = document.createElement("div");
        card.className = "card";

        const img = document.createElement("img");
        img.src =
          item.foto && item.foto.trim() !== ""
            ? `foto/${item.foto}.png`
            : defaultFoto;

        const info = document.createElement("div");
        info.innerHTML = `<h3>${item.nama}</h3>
          ${
            item.nomor
              ? `
            <p><b>No:</b> ${item.nomor}</p>`
              : ""
          }
          ${
            item.tempat_tanggal_lahir
              ? `<p><b>TTL:</b> ${item.tempat_tanggal_lahir}</p>`
              : ""
          }
          ${item.domisili ? `<p><b>Domisili:</b> ${item.domisili}</p>` : ""}
          ${item.kontak ? `<p><b>HP:</b> ${item.kontak}</p>` : ""}
          <p><b>Pengesahan:</b> ${item.pengesahan}</p>
            `;

        card.appendChild(img);
        card.appendChild(info);
        output.appendChild(card);
      });
    }
  }
  // jika tidak ada hasil
  if (output.innerHTML === "") {
    output.innerHTML = "<p><em>Data tidak ditemukan</em></p>";
  }
}

// tampilkan semua data saat pertama kali
renderData();

// event pencarian
searchInput.addEventListener("keyup", () => {
  renderData(searchInput.value);
});
